### PR TITLE
Add uuid() function

### PR DESCRIPTION
**Pull request by deajan**
id() output is not constant, can be uuid or single string.
Add uuid() function that will create an uuid from id() regardless of it's output.

### CODE REVIEW

**Comment by deajan** [comment]
PS: sorry, didn't write the tests for this one since I use pytest ^^

**Comment by ezekg** [comment]
This was already proposed and rejected in https://github.com/keygen-sh/py-machineid/pull/7. This isn't a format I want to officially support, and it's easy enough to implement outside of this library when needed.

**Comment by ezekg** [comment]
Various formats are not something I want to support. You can use the resulting `.id()` bytes to format it as you see fit, but as I said, I do not want to add formatting into this library because formatting is subjective.

**Comment by deajan** [comment]
Fair enough. Your lib, your choice.

**Pull request closed without merging**
