### PR TITLE
Adding a Uniform Format Function

### PR DESCRIPTION
**Pull request by hrh233**
As you may know, machineid is often used to generate globally unique serial numbers such as order number, flow number, transaction version number. Therefore, it would be helpful to have a standardized format for the output, and the hashed_id you provide may not suit many scenarios. I think the uuid format is a good option, and I have written a demo for you.You can amend the code according to your preferences and requirements.

### CODE REVIEW

**Comment by ezekg** [comment]
This PR is pretty hard to review since you've reformatted the entire code base. But regardless, I think this falls into preference territory, so I don't think it makes sense to include another format. The raw ID and hashed ID give you the bytes needed to do this custom format yourself.

**Comment by hrh233** [comment]
> This PR is pretty hard to review since you've reformatted the entire code base. But regardless, I think this falls into preference territory, so I don't think it makes sense to include another format. The raw ID and hashed ID give you the bytes needed to do this custom format yourself.

@ezekg I think it's still important to add a uuid format, as a reply on StackOverFlow said
>Machine id has a more standardised format - [see RFC4122](https://www.rfc-editor.org/rfc/rfc4122).

The text can be found at <https://stackoverflow.com/a/63148464/22123364>

As for the formatting, I can resubmit a non-reformatted PR if you like.

Thanks for your support and understanding!

**Comment by ezekg** [comment]
Aren't all of these IDs _already_ GUIDs? For example, macOS's `IOPlatformUUID` is a UUID; Window's device IDs, e.g. `MachineGuid` and `Win32_ComputerSystemProduct.UUID`, are UUIDs; Linux's `/etc/machine-id` is a UUID, OpenBSD's `smbios.system.uuid` is a UUID. What is the purpose of re-encoding these as a GUID when they already are? The only exception here would be the Docker container IDs, which seem to be SHA digests.

Like I said before, I just don't see this as a wide enough problem to make it a core part of this library.

**Comment by hrh233** [comment]
> Aren't all of these IDs _already_ GUIDs? For example, macOS's `IOPlatformUUID` is a UUID; Window's device IDs, e.g. `MachineGuid` and `Win32_ComputerSystemProduct.UUID`, are UUIDs; Linux's `/etc/machine-id` is a UUID, OpenBSD's `smbios.system.uuid` is a UUID. What is the purpose of re-encoding these as a GUID when they already are? The only exception here would be the Docker container IDs, which seem to be SHA digests.
> 
> Like I said before, I just don't see this as a wide enough problem to make it a core part of this library.

@ezekg My source for this PR is that on my Ubuntu system, I receive the following output when utilizing this library. I am curious as to whether you can repro it.
```python
Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import machineid
>>> machineid.id()
'e8e117f5633f4017850ff73ff65ce223\n'
```

**Comment by ezekg** [comment]
Ah, you're right. I was running in a WSL subsystem so my machine ID showed up as my Window's machine ID.

Just tried it in a Linux container and got the following:

```py
import machineid
print(machineid.id())
# => 8f849e001c660d01914728f8bd46a0546143af30521b5a2ed0ae96a199fb4534
```

Regardless, I still don't think adding this makes sense. It's easy enough to do outside of this library, as needed. To me, it seems like a rather niche use-case and I don't want to complicate this library if it's not required for the majority use-case.

**Comment by hrh233** [comment]
> Ah, you're right. I was running in a WSL subsystem so my machine ID showed up as my Window's machine ID.
> 
> Just tried it in a Linux container and got the following:
> 
> ```python
> import machineid
> print(machineid.id())
> # => 8f849e001c660d01914728f8bd46a0546143af30521b5a2ed0ae96a199fb4534
> ```
> 
> Regardless, I still don't think adding this makes sense. It's easy enough to do outside of this library, as needed. To me, it seems like a rather niche use-case and I don't want to complicate this library if it's not required for the majority use-case.

Thank you for your response. I comprehend your perspective, but I maintain that it is logical to include this feature. This feature would simplify the process of obtaining the formalised machine ID for users, eliminating the need for additional code to be written by them. This requirement is not niche, but rather a frequent occurrence, for example, in determining distinct nodes in a decentralised system. I do not believe this feature will complicate the library since it is merely an optional parameter that does not impact the customary use of other features. I would appreciate it if you would reconsider my proposal. Thank you.

**Comment by ezekg** [comment]
I don't see how using `machineid.id()` or `machineid.hashed_id()` would not already accomplish those requirements,. There's nothing in those requirements that requires the UUID format. In most systems, a fingerprint is an opaque, reproducible string.

Why specifically do you need a UUID format? Why not a SHA digest? Why not an opaque string?

**Pull request closed without merging**
